### PR TITLE
Added Broome County general.

### PR DESCRIPTION
**Pull request by kdent**

### CODE REVIEW

**Comment by dwillis** [comment]
@kdent thanks! only one issue - can you remove the comma formatting from the `votes` column?

**Comment by kdent** [comment]
Sure, I just pushed a new file with commas removed. By the way, I looked at the Jefferson county file to decide if the commas should be there or not. Should I change 20221108__ny__general__jefferson__precinct.csv to remove commas from that one too?

**Comment by dwillis** [comment]
@kdent thanks - sure, you can fix Jefferson, too - I should have caught that.

**Comment by kdent** [comment]
Sounds good. I'll include the Jefferson county changes in my next pull request.

**Pull request merged**
