### PR TITLE
Add Jefferson Co 2018 general results

### PR DESCRIPTION
**Pull request by jeremiak**
Here are 2018 general election results from Jefferson County, NY. They are [sourced from this Google spreadsheet](https://docs.google.com/spreadsheets/d/18ZiVIKiBh-iahG4I_Ildlkc3u46OlBOyp6hDtjE89oo/edit#gid=376624947) found on the Jefferson Co [BOE website](https://co.jefferson.ny.us/departments/Elections/election-results-2010-present) and generated with [this script](https://github.com/jeremiak/open-elections-utils/tree/master/ny/2018/jefferson-general).

They are mostly complete though I have some questions about how to represent the `Registered Voters` and the `Ballots Cast` offices, which are included in each sheet of the source data.

1. When the office is `Registered Voters` should the `party` and `candidate` values be blank? And should the `votes` column represent the number of voters?

2. When the office is `Ballots Cast`, which race should I refer to? Though each precinct has the same number or registered voters across races, they do not necessarily have matching counts of total ballots cast. Do you have a method for determining which race to use for this number?

Thanks!

### CODE REVIEW

**Comment by dwillis** [comment]
@jeremiak Thanks! To answer your questions:

1. `party` and `candidate` are blank for Registered Voters and Ballots Cast.
2. If Ballots Cast are only available by race, use the highest statewide office (in this case, U.S. Senate).

**Comment by jeremiak** [comment]
👍 @dwillis! I'll give you another mention here when I have updated the CSV to include those two "offices."

**Comment by jeremiak** [comment]
@dwillis This is ready for review as both total ballots cast and registration values are in the CSV.

**Comment by dwillis** [comment]
@jeremiak thanks!

**Pull request merged**
