### PR TITLE
Add 2022 general precinct results for NYC

### PR DESCRIPTION
**Pull request by palewire**
For #127 

Districts and parties have been left null. The precinct IDs appear to be provided in two columns. I've concatenated them in the same style I saw in the NYC election board's PDFs.

Screenshot from 2023-01-10 15-00-21

### CODE REVIEW

**Comment by palewire** [comment]
Looks like I'm need to find the district numbers yet for assembly, senate and other numbered offices. I regret the error.

**Comment by palewire** [comment]
Okay. Districts are in there now.

**Comment by palewire** [comment]
It looks like we have some commas in the vote totals. Do you want me to parse those into integers are leave them as they are?

**Comment by dwillis** [comment]
@palewire thanks! integers, please.

**Comment by palewire** [comment]
Copy. Integers are parsed and the files are ready for your review.

**Comment by dwillis** [comment]
@palewire awesome. for offices that are elected borough-wide, like Governor, we leave the `district` column blank.

**Comment by warwickmm** [comment]
@palewire, it appears that several files may have duplicate entries.  For example,

<details><summary>2022/20221108__ny__general__queens__precinct.csv</summary>

  ======================================================================
  FAIL: test_duplicate_entries (data_tests.test_data.DuplicateEntriesTest.test_duplicate_entries) [2022/20221108__ny__general__queens__precinct.csv] (group='2022')
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 97, in test_duplicate_entries
      self._assertTrue(data_test.passed, f"{self} [{short_path}]", short_message, full_message)
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 54, in _assertTrue
      self.assertTrue(result, short_message)
  AssertionError: False is not true : 89583 duplicate entries detected:
  
  	Headers: ['county', 'precinct', 'office', 'district', 'party', 'candidate', 'votes']:
  	Row 2: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '1071']
  	Row 89585: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '1071']
  	Row 3: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 89586: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 4: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '57']
  	Row 89587: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '57']
  	Row 5: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '0']
  	Row 89588: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '0']
  	Row 6: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '11']
  	Row 89589: ['Queens', '001/23', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '11']
  	[Truncated to 10 examples]
  
  </details>
  <details><summary>2022/20221108__ny__general__bronx__precinct.csv</summary>

  ======================================================================
  FAIL: test_duplicate_entries (data_tests.test_data.DuplicateEntriesTest.test_duplicate_entries) [2022/20221108__ny__general__bronx__precinct.csv] (group='2022')
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 97, in test_duplicate_entries
      self._assertTrue(data_test.passed, f"{self} [{short_path}]", short_message, full_message)
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 54, in _assertTrue
      self.assertTrue(result, short_message)
  AssertionError: False is not true : 49363 duplicate entries detected:
  
  	Headers: ['county', 'precinct', 'office', 'district', 'party', 'candidate', 'votes']:
  	Row 2: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '268']
  	Row 49365: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '268']
  	Row 3: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 49366: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 4: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '12']
  	Row 49367: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '12']
  	Row 5: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '1']
  	Row 49368: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '1']
  	Row 6: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '4']
  	Row 49369: ['Bronx', '001/77', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '4']
  	[Truncated to 10 examples]
  
  </details>
  <details><summary>2022/20221108__ny__general__new_york__precinct.csv</summary>

  ======================================================================
  FAIL: test_duplicate_entries (data_tests.test_data.DuplicateEntriesTest.test_duplicate_entries) [2022/20221108__ny__general__new_york__precinct.csv] (group='2022')
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 97, in test_duplicate_entries
      self._assertTrue(data_test.passed, f"{self} [{short_path}]", short_message, full_message)
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 54, in _assertTrue
      self.assertTrue(result, short_message)
  AssertionError: False is not true : 63781 duplicate entries detected:
  
  	Headers: ['county', 'precinct', 'office', 'district', 'party', 'candidate', 'votes']:
  	Row 2: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '585']
  	Row 63783: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '585']
  	Row 3: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 63784: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 4: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '38']
  	Row 63785: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '38']
  	Row 5: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '6']
  	Row 63786: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '6']
  	Row 6: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '39']
  	Row 63787: ['New York', '060/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '39']
  	[Truncated to 10 examples]
  
  </details>
  <details><summary>2022/20221108__ny__general__kings__precinct.csv</summary>

  ======================================================================
  FAIL: test_duplicate_entries (data_tests.test_data.DuplicateEntriesTest.test_duplicate_entries) [2022/20221108__ny__general__kings__precinct.csv] (group='2022')
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 97, in test_duplicate_entries
      self._assertTrue(data_test.passed, f"{self} [{short_path}]", short_message, full_message)
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 54, in _assertTrue
      self.assertTrue(result, short_message)
  AssertionError: False is not true : 99399 duplicate entries detected:
  
  	Headers: ['county', 'precinct', 'office', 'district', 'party', 'candidate', 'votes']:
  	Row 2: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '509']
  	Row 99401: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '509']
  	Row 3: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 99402: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 4: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '26']
  	Row 99403: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '26']
  	Row 5: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '0']
  	Row 99404: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '0']
  	Row 6: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '4']
  	Row 99405: ['Kings', '001/41', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '4']
  	[Truncated to 10 examples]
  
  </details>
  <details><summary>2022/20221108__ny__general__richmond__precinct.csv</summary>

  ======================================================================
  FAIL: test_duplicate_entries (data_tests.test_data.DuplicateEntriesTest.test_duplicate_entries) [2022/20221108__ny__general__richmond__precinct.csv] (group='2022')
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 97, in test_duplicate_entries
      self._assertTrue(data_test.passed, f"{self} [{short_path}]", short_message, full_message)
    File "/home/runner/work/openelections-data-ny/openelections-data-ny/data_tests/data_tests/test_data.py", line 54, in _assertTrue
      self.assertTrue(result, short_message)
  AssertionError: False is not true : 19668 duplicate entries detected:
  
  	Headers: ['county', 'precinct', 'office', 'district', 'party', 'candidate', 'votes']:
  	Row 2: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '450']
  	Row 19670: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Public Counter', '450']
  	Row 3: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 19671: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Manually Counted Emergency', '0']
  	Row 4: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '24']
  	Row 19672: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Absentee / Military', '24']
  	Row 5: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '0']
  	Row 19673: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Federal', '0']
  	Row 6: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '2']
  	Row 19674: ['Richmond', '001/61', 'Governor/Lieutenant Governor', 'NYC', '', 'Affidavit', '2']
  	[Truncated to 10 examples]
</details>

Is this something that is easy to fix?

**Comment by palewire** [comment]
I'm using pandas, so I could quickly knock this out with `drop_duplicates`. I'll give it a closer first to make sure there isn't some meaningful reason for the duplicates.

**Comment by palewire** [comment]
Alright. The latest push attempts to remove duplicates by omitting those citywide files. It also replaces the 'NYC' district with a null value.

**Comment by palewire** [comment]
It looks like those duplicates are from the `Crossover` files you can see [here](https://www.vote.nyc/page/election-results-summary). My reading is that they must be grand totals for districts the run across more than one county. Do you think that's right?

Assuming that's the case, I am going to omit those files now as well.

**Comment by palewire** [comment]
Records from the crossover files have now been removed.

**Pull request merged**
